### ISSUE TITLE
Game crash, I can't make sense of it

### ISSUE THREAD

**Issue by ghost** [spAnser/reacharound#12]
Using Quilt and many other mods, might be conflicting with one of them but I don't know which one it would be

Description: Unexpected error

Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.class_4587.method_46416(float, float, float)'
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61)
	at net.minecraft.client.gui.hud.InGameHud.handler$zip000$reacharound$renderPlacementAssistText(InGameHud:1999)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:394)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:862)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1177)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.method_44604(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_329.handler$zip000$reacharound$renderPlacementAssistText(class_329.java:1999)
	at net.minecraft.class_329.method_1753(class_329.java:394)

-- Affected level --
Details:
	All players: 1 total; [class_746['Wild_Wehttam'/578, l='ClientLevel', x=1169.16, y=-38.00, z=1004.83]]
	Chunk stats: 1024, 204
	Level dimension: minecraft:overworld
	Level spawn location: World: (-383,64,236), Section: (at 1,0,12 in -24,4,14; chunk contains blocks -384,-64,224 to -369,319,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 11288 game time, 20371 day time
	Server brand: quilt
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by spAnser** [comment]
Not Enough Crashes looks like it is for version 1.17.1
Is that what version of Minecraft you are on? That isn't one of the available versions I have built for.

It seems to have an issue with `renderPlacementAssistText` which I am unsure if any mods would modify this function instead of just using it.
