### ISSUE TITLE
Crash on 1.19.3

### ISSUE THREAD

**Issue by nitrogenfive** [spAnser/reacharound#6]
```
[01:26:25] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'net.minecraft.class_1160 net.minecraft.class_2350.method_23955()'
	at com.spanser.reacharound.client.feature.PlacementFeature.getPlacement(PlacementFeature.java:54) ~[reacharound1.19-1.1.0.jar.i0:0/:?]
	at com.spanser.reacharound.client.feature.PlacementFeature.canPlace(PlacementFeature.java:62) ~[reacharound1.19-1.1.0.jar.i0:0/:?]
	at net.minecraft.class_329.handler$bgn000$renderPlacementAssistText(class_329.java:3532) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:910) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1193) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:475) ~[quilt-loader-0.18.1-beta.25.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) ~[quilt-loader-0.18.1-beta.25.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) ~[quilt-loader-0.18.1-beta.25.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

**Comment by spAnser** [comment]
Made a build for 1.19.3
